config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :profiles
  resources :pages
  resources :posts do
    resources :comments
    collection do
      get 'search'
    end
  end

  get 'tags/:tag', to: 'posts#index', as: :tag

  get 'profiles/new'
  post 'profiles/new'

  get 'posts/new'
  post 'posts/new'
  post 'posts/publish'

  get 'static_pages/home'

  root 'static_pages#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  self.per_page = 10
  validates :title, presence: true, length: {maximum: 250}
  validates :user_id, presence: true

  has_attached_file :title_image, styles: { medium: "600x600>", thumb: "100x100>", large: "1000x1000>" }
  validates_attachment :title_image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  acts_as_taggable

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_post, only: [:edit, :update, :destroy, :show]

  def index
    if signed_in?
      @posts = current_user.posts.order!(:published_at)
    else
      @posts = Post.where(published: true).order("published_at DESC")
    end
    if params[:tag]
      @posts = @posts.tagged_with(params[:tag])
    end
    @posts = @posts.paginate(page: params[:page])
  end

  def create
    post_create("create")
  end

  def new
    @post = Post.new
  end

  def show
  end

  def edit
  end

  def publish
    post_create("publish")
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def update
    @post.update(post_params)
    redirect_to post_path(@post.id)
  end

  def search
    if signed_in?
      @posts = Post.where("upper(title) LIKE ? or upper(content) LIKE ?", "%"+params[:q].upcase+"%", "%"+params[:q].upcase+"%")
                   .order("published_at DESC")
                   .paginate(page: params[:page])
    else
      @posts = Post.where(published: true)
                   .where("upper(title) LIKE ? or upper(content) LIKE ?", "%"+params[:q].upcase+"%", "%"+params[:q].upcase+"%")
                   .order("published_at DESC")
                   .paginate(page: params[:page])
    end
    if @posts.count == 0
      flash[:warning] = "Nothing found"
    end
    render 'posts/index'
  end

  private

  def set_post
    if signed_in?
      @post = Post.find(params[:id])
    else
      @post = Post.where(published: true).find(params[:id])
    end
  rescue ActiveRecord::RecordNotFound
    flash[:warning] = "Nothing found"
    redirect_to root_path
  end

  def post_params
    params.require(:post).permit(:title, :content, :published, :title_image, :tag_list, :published_at)
  end

  def post_create(mode)
    @posts = current_user.posts.order("published_at DESC").paginate(page: params[:page])
    @post = current_user.posts.build(post_params)
    @post.published = true if mode == "publish"
    if @post.save
      if mode == "publish"
        flash[:success] = "Post published"
      else
        flash[:success] = "Post created"
      end

      redirect_to root_path
    else
      render 'static_pages/home'
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post, html: { class: 'form-horizontal' }) do |f| %>
  <div class="jumbotron">
    <div class="row">
      <%= f.input :title %>
    </div>
    <div class="row">
      <div class="form-group">
        <% if @post.title_image.exists? %>
            <%= image_tag @post.title_image.url(:medium), class: "img-rounded" %><br>
        <% end %>
        <%= f.label "Title image", class: "control-label" %>
        <%= f.file_field :title_image, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <%= f.input :content, as: :wysihtml5 %>
    </div>
    <div class="row">
      <%= f.input :tag_list, inline_label: "Tags (separated by commas)", input_html: {value: @post.tag_list.join(', ')} %>
    </div>
    <div class="row">
      <div class="col-md-2">
        <%= f.input :published, as: :boolean, label: "Publish" %>
      </div>
        <%= f.input :published_at, as: :datetime, input_html: {value: Time.now} %>
    </div>
    <div class="modal-footer">
      <% if @post.id %>
          <%= f.button :submit, "Save", class: "btn btn-primary" %>
      <% else %>
          <%= f.button :submit, "Publish", class: "btn btn-primary", formaction: posts_publish_path %>
          <%= f.button :submit, "Save", class: "btn btn-default" %>
      <% end %>
      <%= button_to "Cancel", root_path, type: :reset, class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<p>
<div class="panel panel-default">
  <div class="panel-heading clearfix" style="padding: 0px 0px 0px 0px">
  <% if post.title_image.exists? %>
    <div class="post title">
  <% else %>
    <div class="h3" style="margin-left: 15px">
  <% end %>
  <% if post.title_image.exists? %>
     <%= link_to image_tag(post.title_image.url(:large), class: "img-responsive"), post_path(post.id) %>
  <% end %>
  <span>  <% if !post.published %>
  <i class="glyphicon glyphicon-lock"></i>
        <% end %><%= link_to post.title, post_path(post.id), class: "h3" %></span>
  <% if post.title_image.exists? %>
     </div>
  <% else %>
     </div>
  <% end %>
  <div class="timeline">
  <h6><i class="glyphicon glyphicon-calendar" aria-hidden="true"></i><%= post.published_at %>  <i class="glyphicon glyphicon-user" aria-hidden="true"></i><%= Profile.find_by_user_id(post.user_id).nickname %>
    <% if signed_in? %>
        <%= link_to edit_post_path(post.id), class: "btn" do %>
            <i class="glyphicon glyphicon-edit" aria-hidden="true"></i>
        <% end %>
        <%= link_to post, method: :delete,
                    data: { confirm: "You sure?" },
                    title: post.title,
                    class: "btn" do %>
            <i class="glyphicon glyphicon-trash" aria-hidden="true"></i>
        <% end %>
    <% end %>
  </h6>
    <h6><i class="glyphicon glyphicon-tags" aria-hidden="true"></i>
      <%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
    </h6>
  </div>
  </div>
  <div class="panel-body">
    <% if is_index==1 %>
      <%= truncate(strip_tags(post.content), length: 300, separator: ' ') %>
      <p>
        <%= link_to "read full article", post_path(post.id) %>
      </p>
    <% else %>
        <%= post.content.html_safe %>
    <% end %>
  </div>
  <% if is_index==1 %>
  <div class="panel-footer">
  <h5><i class="glyphicon glyphicon-comment" aria-hidden="true"></i>
  Comments: <%= link_to post.comments.count, post_path(post.id, anchor: "comments") %> |
  <a role="button" data-toggle="collapse" href="#collapseForm<%= post.id %>" aria-expanded="false" aria-controls="collapseForm<%= post.id %>">
    Add comment
  </a></h5>
  <div class="collapse" id="collapseForm<%= post.id %>">
    <div class="panel panel-default">
      <%= simple_form_for([post, post.comments.build] , html: { class: 'form-horizontal' }) do |f| %>

          <div class="panel-body" style="margin: 10px 10px 10px 10px;">
            <% if !signed_in? %>
                <%= f.input :nickname %>
                <%= f.input :email %>
            <% end %>
            <%= f.input :content, label: "Comment" %>
          </div>
          <div class="panel-footer">
            <%= f.button :submit, "Add comment", class: "btn btn-primary" %>
            <a role="button" data-toggle="collapse" href="#collapseForm<%= post.id %>" aria-expanded="false" aria-controls="collapseForm<%= post.id %>">
              Cancel
            </a>
          </div>
      <% end %>
    </div>
  </div>
  </div>
  <% end %>
</div>
</p>

app/views/posts/index.html.erb
<%= will_paginate @posts %>

<%= render partial: "posts/post", collection: @posts, locals: { is_index: 1 } %>

<%= will_paginate @posts %>

app/views/posts/show.html.erb
<%= render partial: "post", object: @post, locals: { is_index: 0 } %>
<a id="comments"></a>
<% if @post.comments.count > 0 %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><i class="glyphicon glyphicon-comment" aria-hidden="true"></i> <%= @post.comments.count %> Comment<% if @post.comments.count > 1 %>s<% end %></h4>
      </div>
      <div class="panel-body">
         <% @post.comments.each do |comment| %>
             <%= render comment %>
         <% end %>
      </div>
    </div>
<% end %>
<div class="col-md-12">
<div class="row">
<div class="panel panel-default">
<%= simple_form_for([@post, @post.comments.build] , html: { class: 'form-horizontal' }) do |f| %>

    <div class="panel-body" style="margin: 10px 10px 10px 10px;">
      <% if !signed_in? %>
          <%= f.input :nickname %>
      <% end %>
      <%= f.input :content, label: "Comment" %>
    </div>
    <div class="panel-footer">
      <%= f.button :submit, "Add comment", class: "btn btn-primary" %>
    </div>
<% end %>
</div>
</div>
  </div>