config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :profiles
  resources :pages
  resources :posts do
    resources :comments
    collection do
      get 'search'
    end
  end

  get 'tags/:tag', to: 'posts#index', as: :tag

  get 'profiles/new'
  post 'profiles/new'

  get 'posts/new'
  post 'posts/new'
  post 'posts/publish'

  get 'static_pages/home'

  root 'static_pages#home'

end

app/views/layouts/_favicon.html.erb
<% %w(76 120 152 180).each do |size| %>
    <%= favicon_link_tag "logo.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>

<% %w(16 32).each do |size| %>
    <%= favicon_link_tag "logo_small.png", rel: 'icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>
<!-- link rel="shortcut icon" href="http://swiftbook.ru/favicon.ico" type="image/vnd.microsoft.icon" / -->

app/views/layouts/_footer.html.erb
<footer class="footer">
  Created by Andrey Mikhaylin (Cenobith) in 2016 |
  Glyphicons by <a href="http://glyphicons.com/">Glyphicons</a>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <div class="navbar-brand">
          <%= link_to root_path, id: "logo" do %>
            <%= image_tag('logo_small_white.png') %>
            <%= Blog::Application.config.title %>
          <% end %>
        </div>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <!--ul class="nav nav-pills pull-right" -->
          <li><%= link_to root_path, id: "HomeLnk" do%>
                <i class="glyphicon glyphicon-home" aria-hidden="true"></i>
                <%= t('home') %>
            <% end %>
          </li>
          <% $pages.each do |page| %>
              <li><%= link_to page.title, page_path(page.id) %></li>
          <% end %>
          <% if signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= userpic_for(current_user, size: 20) %><%= nickname_for(current_user) %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to t('settings'), "#", id: "SettingsLnk" %></li>
                  <% if !current_user.profile.nil? %>
                      <li><%= link_to t('profile'), edit_profile_path(current_user.profile.id), id: "EditProfile" %></li>
                  <% end %>
                  <li><%= link_to "My Posts", posts_path %></li>
                  <% if current_user.admin? %>
                      <li><%= link_to t('admin_panel'), rails_admin_path %></li>
                  <% end %>
                  <li class="divider"></li>
                  <li>
                    <%= link_to t('signout'), destroy_user_session_path, method: "delete", id: "SignOutLnk" %>
                  </li>
                </ul>
              </li>
              <li><%= link_to new_post_path do %>
                    <i class="glyphicon glyphicon-edit" aria-hidden="true"></i>
                <% end %></li>
          <% else %>
              <li>
                <%= link_to "#sign_in", "data-toggle" => "modal" do%>
                    <i class="glyphicon glyphicon-user" aria-hidden="true"></i>
                    <%= t('signin') %>
                <% end %>
              </li>
          <% end %>
          <li><a href="#" role="button" data-toggle="modal" data-target="#myModal">
            <i class="glyphicon glyphicon-search" aria-hidden="true"></i>
          </a>
          </li>
        </ul>
      </nav>
      </div>
    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Find in posts</h4>
      </div>
      <%= form_tag search_posts_path, method: "get" do %>
      <div class="modal-body">
        <%= text_field_tag :q, params[:q], class: "form-control" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag "Find", :name => nil, class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div id="tag_cloud">
      <i class="glyphicon glyphicon-tags" aria-hidden="true"></i>
      <% tag_cloud Post.tag_counts, %w{s m l} do |tag, css_class| %>
        <%= link_to tag.name, tag_path(tag.name), class: css_class %>
      <% end %>
    </div>
    <div class="center">
    <% $widgets.each do |widget| %>
        <p>
          <% if widget.show_pic == true %>
              <% if !widget.link.nil? %>
                  <a href="<%= widget.link %>">
              <% end %>
              <%= image_tag(widget.image.url(:normal), width: widget.width) %>
              <% if !widget.link.nil? %>
                  </a>
              <% end %>

          <% else %>
              <%= widget.content.html_safe %>
          <% end %>
        </p>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/favicon' %>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <meta name="viewport" content="initial-scale = 1.0,maximum-scale = 1.0" />
</head>
<body>
<%= render 'layouts/header' %>
<% if !signed_in? %>
    <%= render 'shared/sign_in' %>
<% end %>
<div class="container">
  <div class="bs3-row">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
    <% end %>
    <div class="col-md-9">
    <%= yield %>
    </div>
    <div class="col-md-3">
      <%= render 'layouts/sidebar' %>
    </div>
  </div>
</div>
<div class="container">
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/layouts/errors.html.erb
<h1>Ooops!</h1>